#!/bin/bash

# current dir
CURR_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
NODE_BIN=${CURR_DIR}/node/bin

# use nodejs install on the system if did not use env_setup
NODE=${NODE_BIN}/node
if [ ! -e "${NODE}" ]; then
  NODE=node
  type ${NODE} >/dev/null 2>&1 || {
    NODE=nodejs
  }
  type ${NODE} >/dev/null 2>&1 || {
    NODE=
  }
  if [ -z "${NODE}" ] || [ $(${NODE} -v) \< 'v0.12.' ]; then
    echo 'Your Node.js version is too low.'
    echo 'You need to install nodejs (>=v0.12.0) or run ./env_setup.'
    exit 1;
  fi
fi

# start web server for the app
cd ${CURR_DIR}
${NODE} webserver.js

